development:
  adapter: postgresql
  encoding: UTF-8
  host:     172.16.10.10
  port:     5432
  database: sexy_votes_development
  username: developer
  password:

test:
  adapter: postgresql
  encoding: UTF-8
  host:     172.16.10.10
  port:     5432
  database: sexy_votes_test
  username: developer
  password:

production:
  adapter: postgresql
  encoding: UTF-8
  host:     172.16.10.10
  port:     5432
  database: sexy_votes_production
  username: sexy_votes
  password:
